### ISSUE TITLE
关于token

### ISSUE THREAD

**Issue by sucangit** [gogobody/WxFans#2]
公众号里token字段必须填写，只要开启服务器配置，自动回复功能就关闭了怎么解决呢？谢谢
![自动回复](https://cdn.jsdelivr.net/gh/sucangit/imageshost/img/20210916125426.png)

后续：是我没明白逻辑。已经搞懂了。用api就不能用自动回复，不启用开发者配置就使用自动回复手动查看。

PS：作者你好快。我正在编辑下面就显示回复了。谢谢

**Comment by gogobody** [comment]
两种方式只能选一种

**Comment by sucangit** [comment]
> 两种方式只能选一种

谢谢 搞懂了
